# For console output
# output: console
# level: info

# For file output
# output: file
# level: info
# file_path: "logs"
# file_name: "app.log"

output: grpc
level: info
grpc:
  address: "0.0.0.0"
  port: 50052
