output: "grpc"
level: "info"
server_id: "semantic-service"
client_id: "semantic-service"
grpc:
  address: "0.0.0.0"
  port: 50052
server:
  address: "0.0.0.0"
  port: 50058
endpoint_client:
  default_address: "http://0.0.0.0:5007"
log_fields:
  include_thread_id: true
  include_target: true
  include_file: true
  include_line: true
  include_timestamp: true
client_retry:
  max_retries: 5000
  base_delay_secs: 1
  reconnect_delay_secs: 5
log_all_messages: false
debug_mode:
  enabled: true
  test_interval_secs: 10
  use_local_endpoints: true
models:
  sentence_to_json:
    ollama: "llama2:latest"
    claude: "claude-3-7-sonnet-20250219"
    temperature: 0.1
    max_tokens: 1000
  find_endpoint:
    claude: "claude-3-7-sonnet-20250219"
    ollama: "deepseek-r1:8b"
    temperature: 0.1
    max_tokens: 500
  semantic_match:
    claude: "claude-3-7-sonnet-20250219"
    ollama: "deepseek-r1:8b"
    temperature: 0.1
    max_tokens: 500
providers:
  ollama:
    enabled: true
    host: "http://localhost:11434"
  claude:
    enabled: false
    api_key: "" # Will be loaded from .env
