output: grpc
level: debug
grpc:
  address: "127.0.0.1"
  port: 50052
log_fields:
  include_thread_id: false
  include_target: false
  include_file: false
  include_line: false
  include_timestamp: false
debug_mode:
  enabled: true
  test_interval_secs: 10
