output: grpc
level: info
server_id: "semantic-service"  # Identifies this service in the logs
client_id: "semantic-service"
grpc:
  address: "127.0.0.1"
  port: 50052 # Port where your grpc-logger server is running
log_fields:
  include_thread_id: true
  include_target: true
  include_file: true
  include_line: true
  include_timestamp: true
client_retry:
  max_retries: 5000
  base_delay_secs: 1
  reconnect_delay_secs: 5
log_all_messages: false

debug_mode:
  enabled: false
  test_interval_secs: 10

# Model configurations
models:
  sentence_to_json:
    name: "llama2"
    temperature: 0.1
    max_tokens: 1000
  find_endpoint:
    name: "deepseek-r1:8b"
    temperature: 0.1
    max_tokens: 500
  semantic_match:
    name: "deepseek-r1:8b"
    temperature: 0.1
    max_tokens: 500

providers:
  ollama:
    enabled: true
    host: "http://localhost:11434"
  claude:
    enabled: false
    api_key: ""  # Will be loaded from .env
